export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE';

export const SAVE_CUSTOMER_REQUEST = 'SAVE_CUSTOMER_REQUEST';
export const SAVE_CUSTOMER_SUCCESS = 'SAVE_CUSTOMER_SUCCESS';
export const SAVE_CUSTOMER_FAILURE = 'SAVE_CUSTOMER_FAILURE';

export const CUSTOMER_SELECTED = "CUSTOMER_SELECTED"
export const UPDATE_SELECTED_CUSTOMER = "UPDATE_SELECTED_CUSTOMER"

export const FETCH_INVOICES_REQUEST = 'FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE';

export const CREATE_NEW_INVOICE = "CREATE_NEW_INVOICE"
export const UPDATE_NEW_INVOICE = "UPDATE_NEW_INVOICE"
export const SAVE_TO_DRAFT = "SAVE_TO_DRAFT"
export const DELETE_FROM_DRAFT = "DELETE_FROM_DRAFT"

export const SAVE_INVOICE_REQUEST = 'SAVE_INVOICE_REQUEST';
export const SAVE_INVOICE_SUCCESS = 'SAVE_INVOICE_SUCCESS';
export const SAVE_INVOICE_FAILURE = 'SAVE_INVOICE_FAILURE';

export const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAILURE = 'DELETE_INVOICE_FAILURE';

export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';